[package]
name = "normalize"
version = "0.1.0"
authors = ["Zibi Braniecki <zibi@braniecki.net>"]
edition = "2018"

[dependencies]
libc = "0.2"
unicode-normalization = "0.1"
detone = "1.0.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "normalize"
harness = false
